version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-local
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: